version: 0.2

phases:
  install:
    commands:
      - yum install -y git
  pre_build:
    commands:
      - echo pre_build start
      # docker imageの取得制限にひっかかるため、docker loginをする。
      - echo ${DOCKER_HUB_TOKEN} | docker login -u ${DOCKER_HUB_NAME} --password-stdin
      # コンテナ内でテストを実施
      - docker-compose up -d
      - docker-compose exec -T cicd_test_app go test -v -cover || exit
  build:
    commands:
      - echo build start
      # ビルド
      - env GOOS=linux GOARCH=amd64 go build main.go
  post_build:
    commands:
      - echo Build completed on `date`
# 成果物をS3に保存する
artifacts:
    files:
        - './main'
      