version: '3'
services:
  cicd_test_app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 80:80
    # depends_on:
      # - "cicd_test_db"

#   cicd_test_db:
#     image: mysql:8.0
#     cap_add:
#       - SYS_NICE # 追加
#     environment:
#       MYSQL_ROOT_PASSWORD: go_root
#       MYSQL_DATABASE: go_db
#       MYSQL_USER: go_user
#       MYSQL_PASSWORD: go_pass
#       # mysql -ugo_wedding_user -pgo_wedding_pass_kkde5
#       TZ: 'Asia/Tokyo'
#     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - db-data:/var/lib/mysql
#       - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
#     ports:
#       - 3306:3306

# volumes:
#   db-data:
#     driver: local